version: '3.3'
services:

  frontend:
    image: lapkipomoshi/help_paw_f:test
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: lapkipomoshi/help_paw:test
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput && 
      python manage.py migrate && 
      gunicorn help_paw.wsgi:application --bind 0:8000"
    volumes:
      - static_value:/app/static_files/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/conf.d/.htpasswd
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static_files/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  postgres: